---
- hosts: all
  become: yes
  tasks:
    - name: Uninstall Nginx
      apt:
        name: nginx
        state: absent

    - name: Remove index.html
      file: 
        state: absent
        path: /var/www/html/index.nginx-debian.html
