pipeline {
    agent any
    stages {
        stage('compile') {
			steps {
                echo 'compiling..'
				git url: 'https://github.com/lerndevops/DevOpsClassCodes'
				sh label: '', script: 'mvn compile'
            }
        }
        stage('codereview-pmd') {
			steps {
                echo 'codereview..'
				sh label: '', script: 'mvn -P metrics pmd:pmd'
            }	
        }
        stage('unit-test') {
			steps {
                echo 'codereview..'
				sh label: '', script: 'mvn test'
            }
			post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
			
        }
        stage('metric-check') {
			steps {
                echo 'unit test..'
				sh label: '', script: 'mvn cobertura:cobertura -Dcobertura.report.format=xml'
            }
			
        }
        stage('package') {
			steps {
                echo 'metric-check..'
				sh label: '', script: 'mvn package'	
            }
			
        }
    }
}
