---
- hosts: all 
#  become: yes
  tasks:
#### copy a file
    - name: copy file
      copy:
        src: /tmp/demo.txt
        dest: /tmp
#### create a folder or file
    - name: Create a new file
      file:
        path: /tmp/newfolder
        state: directory
