apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-thanos-storegateway-0-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/thanos-storage-gateway-volume/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: data-thanos-storegateway-0-pv
  volumeMode: Filesystem
