apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-compactor-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/thanos-compactor-volume/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: thanos-compactor-pv
  volumeMode: Filesystem
