apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-minio-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/thanos-minio-volume/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: thanos-minio-pv
  volumeMode: Filesystem
