apiVersion: v1
kind: Service
metadata:
  name: thanos-minio-np
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: minio-console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort
