apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/component: query
  name: thanos-query-np
  namespace: monitoring
spec:
  ports:
  - name: thanos-query
    nodePort: 30015
    port: 10902
    protocol: TCP
    targetPort: 10902
  selector:
    app.kubernetes.io/component: query
  type: NodePort
